ALTER DATABASE PcPonto SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
BEGIN TRANSACTION;
    DBCC CHECKDB (PcPonto, REPAIR_ALLOW_DATA_LOSS);
    ALTER DATABASE PcPonto SET MULTI_USER;
COMMIT;
DBCC CHECKDB('PcPonto') WITH NO_INFOMSGS, ALL_ERRORMSGS